import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  // Create leads table for CRM functionality
  await knex.schema.raw(`
    CREATE TABLE leads (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      first_name VARCHAR(255),
      last_name VARCHAR(255),
      email VARCHAR(255) NOT NULL,
      phone VARCHAR(50),
      source VARCHAR(100), -- 'ppc', 'organic', 'direct', 'referral', 'website', 'facebook', 'zillow'
      status VARCHAR(50) DEFAULT 'new', -- 'new', 'contacted', 'qualified', 'showing', 'offer', 'under_contract', 'closed', 'lost'
      assigned_to VARCHAR(255), -- Agent email
      property_interest TEXT,
      tags JSONB DEFAULT '[]',
      custom_fields JSONB DEFAULT '{}',
      notes TEXT,
      last_contact_at TIMESTAMP,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create lead activities table for activity timeline
  await knex.schema.raw(`
    CREATE TABLE lead_activities (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
      activity_type VARCHAR(100) NOT NULL, -- 'call', 'email', 'meeting', 'status_change', 'note', 'property_view', 'form_submission'
      description TEXT,
      performed_by VARCHAR(255), -- Agent email
      metadata JSONB DEFAULT '{}',
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create analytics events table
  await knex.schema.raw(`
    CREATE TABLE analytics_events (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      event_type VARCHAR(100) NOT NULL, -- 'page_view', 'lead_created', 'property_view', 'search', 'contact_form', 'favorite'
      user_email VARCHAR(255),
      properties JSONB DEFAULT '{}', -- Custom event properties
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create analytics metrics table (pre-aggregated metrics)
  await knex.schema.raw(`
    CREATE TABLE analytics_metrics (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      metric_name VARCHAR(100) NOT NULL, -- 'total_leads', 'page_views', 'conversion_rate', 'active_listings'
      metric_value DECIMAL(10,2) NOT NULL,
      date DATE NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(org_id, metric_name, date)
    )
  `);

  // Create content pages table
  await knex.schema.raw(`
    CREATE TABLE content_pages (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      title VARCHAR(255) NOT NULL,
      slug VARCHAR(255) NOT NULL,
      content JSONB DEFAULT '{}', -- { modules: [], sidebar: [] }
      status VARCHAR(50) DEFAULT 'draft', -- 'draft', 'published'
      featured_image_url TEXT,
      featured_image_cloudinary_id VARCHAR(255),
      is_template BOOLEAN DEFAULT false,
      template_name VARCHAR(255),
      parent_page_id BIGINT REFERENCES content_pages(id),
      category VARCHAR(100),
      meta_title VARCHAR(255),
      meta_description TEXT,
      meta_keywords JSONB DEFAULT '[]',
      robots VARCHAR(50) DEFAULT 'index,follow', -- For agent pages: 'noindex,nofollow'
      custom_css TEXT,
      custom_js TEXT,
      published_at TIMESTAMP,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(org_id, slug)
    )
  `);

  // Create testimonials table
  await knex.schema.raw(`
    CREATE TABLE testimonials (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      client_name VARCHAR(255) NOT NULL,
      client_role VARCHAR(255),
      content TEXT NOT NULL,
      rating INTEGER CHECK (rating >= 1 AND rating <= 5),
      agent_email VARCHAR(255),
      property_address TEXT,
      featured BOOLEAN DEFAULT false,
      published BOOLEAN DEFAULT true,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create navigation items table
  await knex.schema.raw(`
    CREATE TABLE navigation_items (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      label VARCHAR(255) NOT NULL,
      type VARCHAR(50) NOT NULL, -- 'internal', 'external', 'dropdown'
      url VARCHAR(500),
      icon VARCHAR(100), -- Lucide icon name or MUI icon name
      position VARCHAR(50) NOT NULL, -- 'left', 'right', 'mobile'
      dropdown_items JSONB DEFAULT '[]', -- For dropdown type
      target VARCHAR(20) DEFAULT '_self', -- '_self', '_blank'
      css_classes TEXT,
      visible BOOLEAN DEFAULT true,
      order_index INTEGER DEFAULT 0,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create SEO settings table
  await knex.schema.raw(`
    CREATE TABLE seo_settings (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE UNIQUE,
      default_meta_title VARCHAR(255),
      default_meta_description TEXT,
      index_property_pages BOOLEAN DEFAULT false,
      robots_txt TEXT,
      canonical_url VARCHAR(500),
      og_defaults JSONB DEFAULT '{}',
      sitemap_generated_at TIMESTAMP,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create indexes
  await knex.schema.raw(`
    CREATE INDEX idx_leads_org_status ON leads(org_id, status);
    CREATE INDEX idx_leads_assigned_to ON leads(assigned_to);
    CREATE INDEX idx_leads_created ON leads(created_at DESC);
    CREATE INDEX idx_lead_activities_lead ON lead_activities(lead_id, created_at DESC);
    CREATE INDEX idx_lead_activities_org ON lead_activities(org_id);
    CREATE INDEX idx_analytics_events_org ON analytics_events(org_id, event_type, created_at);
    CREATE INDEX idx_analytics_metrics_org ON analytics_metrics(org_id, metric_name, date);
    CREATE INDEX idx_content_pages_org_slug ON content_pages(org_id, slug);
    CREATE INDEX idx_content_pages_status ON content_pages(org_id, status);
    CREATE INDEX idx_testimonials_org ON testimonials(org_id, published);
    CREATE INDEX idx_nav_items_org_pos ON navigation_items(org_id, position, order_index);
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('seo_settings');
  await knex.schema.dropTableIfExists('navigation_items');
  await knex.schema.dropTableIfExists('testimonials');
  await knex.schema.dropTableIfExists('content_pages');
  await knex.schema.dropTableIfExists('analytics_metrics');
  await knex.schema.dropTableIfExists('analytics_events');
  await knex.schema.dropTableIfExists('lead_activities');
  await knex.schema.dropTableIfExists('leads');
}
