import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  // Create organizations table (SAAS customers - real estate brokerages)
  await knex.schema.raw(`
    CREATE TABLE organizations (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name VARCHAR(255) NOT NULL,
      slug VARCHAR(100) NOT NULL UNIQUE,
      plan VARCHAR(50) DEFAULT 'trial', -- 'trial', 'starter', 'professional', 'enterprise'
      status VARCHAR(50) DEFAULT 'active', -- 'active', 'suspended', 'cancelled'
      settings JSONB DEFAULT '{}', -- Custom branding, features enabled, etc.
      stripe_customer_id VARCHAR(255),
      stripe_subscription_id VARCHAR(255),
      trial_ends_at TIMESTAMP,
      primary_domain VARCHAR(255), -- Main domain for this organization (e.g., 'realtorsite.com')
      custom_domain VARCHAR(255), -- Custom domain if configured
      logo_cloudinary_id VARCHAR(255),
      primary_color VARCHAR(7) DEFAULT '#1976d2',
      secondary_color VARCHAR(7) DEFAULT '#dc004e',
      contact_email VARCHAR(255),
      contact_phone VARCHAR(50),
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create organization members table
  await knex.schema.raw(`
    CREATE TABLE organization_members (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      email VARCHAR(255) NOT NULL,
      role VARCHAR(50) NOT NULL, -- 'owner', 'admin', 'agent', 'member'
      invited_by VARCHAR(255),
      invited_at TIMESTAMP,
      joined_at TIMESTAMP,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(org_id, email)
    )
  `);

  // Create invitations table
  await knex.schema.raw(`
    CREATE TABLE invitations (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      email VARCHAR(255) NOT NULL,
      role VARCHAR(50) NOT NULL,
      token VARCHAR(255) NOT NULL UNIQUE,
      invited_by VARCHAR(255),
      expires_at TIMESTAMP,
      accepted_at TIMESTAMP,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create organization usage tracking table (for billing)
  await knex.schema.raw(`
    CREATE TABLE organization_usage (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
      metric VARCHAR(100) NOT NULL, -- 'api_calls', 'storage_mb', 'users', 'leads', 'pages'
      value INTEGER NOT NULL,
      period_start TIMESTAMP NOT NULL,
      period_end TIMESTAMP NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create indexes
  await knex.schema.raw(`
    CREATE INDEX idx_org_members_org_id ON organization_members(org_id);
    CREATE INDEX idx_org_members_email ON organization_members(email);
    CREATE INDEX idx_invitations_org_id ON invitations(org_id);
    CREATE INDEX idx_invitations_token ON invitations(token);
    CREATE INDEX idx_org_usage_org_id ON organization_usage(org_id, period_start);
  `);

  // Add org_id to existing ACL table
  await knex.schema.raw(`
    ALTER TABLE acl ADD COLUMN org_id BIGINT REFERENCES organizations(id);
    CREATE INDEX idx_acl_org_id ON acl(org_id);
  `);

  // Enhance agents table with subdomain support (if table doesn't exist, create it)
  const hasAgentsTable = await knex.schema.hasTable('agents');

  if (!hasAgentsTable) {
    await knex.schema.raw(`
      CREATE TABLE agents (
        id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        user_id VARCHAR(255), -- Link to auth user
        email VARCHAR(255) NOT NULL,
        first_name VARCHAR(255),
        last_name VARCHAR(255),
        full_name VARCHAR(255),
        phone VARCHAR(50),
        license_number VARCHAR(100),
        bio TEXT,
        profile_image_cloudinary_id VARCHAR(255),
        subdomain VARCHAR(100), -- Agent's subdomain (e.g., 'john-smith' in john-smith.realtorsite.com)
        agent_id VARCHAR(100), -- External agent ID (e.g., Follow Up Boss)
        years_experience INTEGER,
        specialties JSONB DEFAULT '[]',
        languages JSONB DEFAULT '[]',
        social_links JSONB DEFAULT '{}',
        active BOOLEAN DEFAULT true,
        featured BOOLEAN DEFAULT false,
        sort_order INTEGER DEFAULT 0,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(org_id, email),
        UNIQUE(org_id, subdomain)
      )
    `);

    await knex.schema.raw(`
      CREATE INDEX idx_agents_org_id ON agents(org_id);
      CREATE INDEX idx_agents_email ON agents(email);
      CREATE INDEX idx_agents_subdomain ON agents(org_id, subdomain);
    `);
  } else {
    // If agents table exists, add new columns
    await knex.schema.raw(`
      ALTER TABLE agents
        ADD COLUMN IF NOT EXISTS org_id BIGINT REFERENCES organizations(id) ON DELETE CASCADE,
        ADD COLUMN IF NOT EXISTS subdomain VARCHAR(100),
        ADD COLUMN IF NOT EXISTS profile_image_cloudinary_id VARCHAR(255),
        ADD COLUMN IF NOT EXISTS specialties JSONB DEFAULT '[]',
        ADD COLUMN IF NOT EXISTS languages JSONB DEFAULT '[]',
        ADD COLUMN IF NOT EXISTS social_links JSONB DEFAULT '{}';

      CREATE INDEX IF NOT EXISTS idx_agents_org_id ON agents(org_id);
      CREATE INDEX IF NOT EXISTS idx_agents_subdomain ON agents(org_id, subdomain);
    `);
  }

  // Add org_id to existing tables
  await knex.schema.raw(`
    ALTER TABLE blogs ADD COLUMN IF NOT EXISTS org_id BIGINT REFERENCES organizations(id);
    CREATE INDEX IF NOT EXISTS idx_blogs_org_id ON blogs(org_id);
  `);

  await knex.schema.raw(`
    ALTER TABLE admin_settings ADD COLUMN IF NOT EXISTS org_id BIGINT REFERENCES organizations(id);
    CREATE INDEX IF NOT EXISTS idx_admin_settings_org_id ON admin_settings(org_id);
  `);

  await knex.schema.raw(`
    ALTER TABLE assets ADD COLUMN IF NOT EXISTS org_id BIGINT REFERENCES organizations(id);
    CREATE INDEX IF NOT EXISTS idx_assets_org_id ON assets(org_id);
  `);

  // Create default organization
  await knex.schema.raw(`
    INSERT INTO organizations (
      name,
      slug,
      plan,
      status,
      primary_domain,
      trial_ends_at
    ) VALUES (
      'Default Organization',
      'default',
      'enterprise',
      'active',
      'localhost',
      NULL
    )
    ON CONFLICT DO NOTHING
  `);

  // Get the default org ID and update existing data
  await knex.schema.raw(`
    WITH default_org AS (
      SELECT id FROM organizations WHERE slug = 'default' LIMIT 1
    )
    UPDATE acl SET org_id = (SELECT id FROM default_org) WHERE org_id IS NULL;
  `);

  await knex.schema.raw(`
    WITH default_org AS (
      SELECT id FROM organizations WHERE slug = 'default' LIMIT 1
    )
    UPDATE blogs SET org_id = (SELECT id FROM default_org) WHERE org_id IS NULL;
  `);

  await knex.schema.raw(`
    WITH default_org AS (
      SELECT id FROM organizations WHERE slug = 'default' LIMIT 1
    )
    UPDATE admin_settings SET org_id = (SELECT id FROM default_org) WHERE org_id IS NULL;
  `);

  await knex.schema.raw(`
    WITH default_org AS (
      SELECT id FROM organizations WHERE slug = 'default' LIMIT 1
    )
    UPDATE assets SET org_id = (SELECT id FROM default_org) WHERE org_id IS NULL;
  `);

  // Create organization members from existing ACL
  await knex.schema.raw(`
    WITH default_org AS (
      SELECT id FROM organizations WHERE slug = 'default' LIMIT 1
    )
    INSERT INTO organization_members (org_id, email, role, joined_at)
    SELECT
      (SELECT id FROM default_org),
      email,
      CASE
        WHEN role = 1 THEN 'owner'  -- Root
        WHEN role = 3 THEN 'admin'  -- Admin
        WHEN role = 4 THEN 'agent'  -- Agent
        ELSE 'member'               -- User
      END,
      created_at
    FROM acl
    ON CONFLICT (org_id, email) DO NOTHING;
  `);
}

export async function down(knex: Knex): Promise<void> {
  // Remove org_id from existing tables
  await knex.schema.raw(`
    DROP INDEX IF EXISTS idx_assets_org_id;
    ALTER TABLE assets DROP COLUMN IF EXISTS org_id;
  `);

  await knex.schema.raw(`
    DROP INDEX IF EXISTS idx_admin_settings_org_id;
    ALTER TABLE admin_settings DROP COLUMN IF EXISTS org_id;
  `);

  await knex.schema.raw(`
    DROP INDEX IF EXISTS idx_blogs_org_id;
    ALTER TABLE blogs DROP COLUMN IF EXISTS org_id;
  `);

  await knex.schema.raw(`
    DROP INDEX IF EXISTS idx_agents_subdomain;
    DROP INDEX IF EXISTS idx_agents_org_id;
    ALTER TABLE agents DROP COLUMN IF EXISTS social_links;
    ALTER TABLE agents DROP COLUMN IF EXISTS languages;
    ALTER TABLE agents DROP COLUMN IF EXISTS specialties;
    ALTER TABLE agents DROP COLUMN IF EXISTS profile_image_cloudinary_id;
    ALTER TABLE agents DROP COLUMN IF EXISTS subdomain;
    ALTER TABLE agents DROP COLUMN IF EXISTS org_id;
  `);

  await knex.schema.raw(`
    DROP INDEX IF EXISTS idx_acl_org_id;
    ALTER TABLE acl DROP COLUMN IF EXISTS org_id;
  `);

  // Drop new tables
  await knex.schema.dropTableIfExists('organization_usage');
  await knex.schema.dropTableIfExists('invitations');
  await knex.schema.dropTableIfExists('organization_members');
  await knex.schema.dropTableIfExists('organizations');
}
