import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  await knex.schema.raw(`create table admin_settings (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key varchar NOT NULL UNIQUE,
    value jsonb not null,
    description text,
    updated_by varchar,
    created_at TIMESTAMP without time zone not null default CURRENT_TIMESTAMP,
    updated_at TIMESTAMP without time zone not null default CURRENT_TIMESTAMP
  )`);

  // Insert default settings for PPC registration
  await knex.schema.raw(`insert into admin_settings (key, value, description) values
    ('ppc_registration_required', '{"enabled": true, "sources": ["ppc", "cpc", "paid"]}'::jsonb, 'Force registration on first property view for paid traffic sources'),
    ('organic_registration_optional', '{"enabled": true}'::jsonb, 'Show optional registration modal for organic traffic')
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTable("admin_settings");
}
