import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  // Add traffic source tracking fields to support PPC vs organic differentiation
  // Note: This assumes clients table exists in the connected database
  // If clients is managed externally, these fields should be stored in a separate tracking table

  await knex.schema.raw(`create table if not exists client_traffic_sources (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id bigint NOT NULL,
    utm_source varchar,
    utm_medium varchar,
    utm_campaign varchar,
    utm_term varchar,
    utm_content varchar,
    traffic_type varchar, -- 'ppc', 'organic', 'direct', 'referral', etc.
    referer text,
    landing_page text,
    created_at TIMESTAMP without time zone not null default CURRENT_TIMESTAMP
  )`);

  // Create index for efficient lookups
  await knex.schema.raw(`create index idx_client_traffic_sources_client_id on client_traffic_sources(client_id)`);
  await knex.schema.raw(`create index idx_client_traffic_sources_traffic_type on client_traffic_sources(traffic_type)`);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTable("client_traffic_sources");
}
