import crypto from 'node:crypto'
import { promisify } from 'node:util'
import type { Knex } from 'knex'

const scryptAsync = promisify(crypto.scrypt)

async function hashPassword(password: string): Promise<string> {
  const salt = crypto.randomBytes(16).toString('hex')
  const derived = (await scryptAsync(password, salt, 64)) as Buffer
  return `${salt}:${derived.toString('hex')}`
}

export async function up(knex: Knex): Promise<void> {
  await knex.schema.raw(`
    CREATE TABLE admin_users (
      id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      email VARCHAR(255) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      first_name VARCHAR(255),
      last_name VARCHAR(255),
      role VARCHAR(50) NOT NULL DEFAULT 'admin',
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `)

  // Seed Andy's admin account
  const passwordHash = await hashPassword('Jaxon2022!@')
  await knex('admin_users').insert({
    email: 'andy@mandelteam.com',
    password_hash: passwordHash,
    first_name: 'Andy',
    last_name: 'Mandel',
    role: 'admin'
  })
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('admin_users')
}
